services:
  - type: web
    name: tyangge-bot
    env: node
    plan: starter
    buildCommand: npm ci --omit=dev
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 1
